### ISSUE TITLE
Zonestamp breaks when a query parameter is added

### ISSUE THREAD

**Issue by chicocvenancio** [hartman/zonestamp#11]
Original https://github.com/hartman/zonestamp-toolforge/issues/1 by @tgr
>Works: https://zonestamp.toolforge.org/1618671635
> Doesn't work: https://zonestamp.toolforge.org/1618671635?fbclid=IwAR3bJL9ows_qdHHrsXwMvBRtErrvBsVdMD8XinrX2k9RE3bV7916Z4Yq_dI
> 
> Obviously this is a big problem for sharing events on social media.
> 
> Upstream does not seem to have this issue: https://zonestamp.com/1617962599?fbclid=IwAR3bJL9ows_qdHHrsXwMvBRtErrvBsVdMD8XinrX2k9RE3bV7916Z4Yq_dI

**Comment by hartman** [comment]
We modified the .lighttpd file config
Then we learned we had to do webservice stop/start instead of webservice restart
