### ISSUE TITLE
"Make your own zoneStamp" timestamp should floor() the seconds

### ISSUE THREAD

**Issue by NovemLinguae** [hartman/zonestamp#18]
Steps to reproduce
* Visit https://zonestamp.toolforge.org/
* Pick a date and time (I was using 4th May 2023 17:00 UTC)
* Click "Generate stamp"

What happens?
* URL contains a timestamp that, when converted back to human readable time, ends in a random number of seconds, such as :37 seconds

What should happen instead?
* URL contains a timestamp that, when converted back to human readable time, ends in :00 seconds

**Comment by hartman** [comment]
You mean the seconds offset ?  its indeed based on the current time. Note however that setting it to 0 will not make the url end in 00 but on a multiple of 60, as unixtimestamps are just an amount of seconds, and don't wrap on 60 seconds ;)

**Comment by NovemLinguae** [comment]
Yes good point about the multiple of 60, I misspoke. Will correct the ticket.
