### ISSUE TITLE
Invalid date

### ISSUE THREAD

**Issue by ealescak** [hartman/zonestamp#20]
Hi! I'm trying to create a new Zonestamp, but when I enter the future date and time, the response is 'invalid date.' My colleague is having the same problem. I've been using the tool reliably for a couple of years and this is the first time I've encountered this issue.  Thanks for your help!

**Comment by hartman** [comment]
Its new a known issue for creating a new stamp. if you refresh the page, it should have the correct time.

I'll hopefully fix that this weekend.

**Comment by ealescak** [comment]
thanks! :-)
