### ISSUE TITLE
Calendar timestamps are broken

### ISSUE THREAD

**Issue by tgr** [hartman/zonestamp#26]
Given this zonestamp:

https://zonestamp.toolforge.org/1696521600?enddate=1696525200&name=MCDC+community+open+session&description=Zoom+link:+https://wikimedia.zoom.us/meeting/register/tZcsc-uvrz4pHNyicRTaLYxiGbg1J3Shub9i

the calendar should generate an UTC 16h-17h, but actually it's 10h-10h (the day is correct).

The .ics has
DTSTART;TZID=Etc/GMT:20231005T100000
DTEND;TZID=Etc/GMT:20231005T100000

and also
DTSTART:19700101T000000
which, I don't know much about ics but seems wrong, but I guess that's an unrelated issue with the calendar widget itself.

**Comment by hartman** [comment]
Sorry, I had missed this

Ugh I really need to rewrite all this to get rid of moment. there's too many interdependent components now that all turn this into a bit of a mess.

I'll try and take a look later today.

**Comment by hartman** [comment]
The `DTSTART:19700101T000000` is inside a VTIMEZONE block. It's supposed to indicate from which moment in time the definition of this timezone became in use. For UTC that doesn't really exist, so it uses epoch.
