### ISSUE TITLE
Add iCal option

### ISSUE THREAD

**Issue by hartman** [hartman/zonestamp#6]
Create an option to download the time as an ics iCal event

Could also use several arguments from the url like a description ?

**Comment by tgr** [comment]
Upstream task is https://github.com/raquelmsmith/zonestamp/issues/5.

A dedicated import button for common calendar apps (maybe via [jekuer/add-to-calendar-button](https://github.com/jekuer/add-to-calendar-button) or a similar library) would be even cooler.
